<?php
function welcome_user_menu() {
    $items['welcome'] = array(
        'title' => 'Thanks for visiting',
        'page callback' => 'welcome_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function bakery_user_user_login() {
    $_GET['destination'] = 'welcome';
}

function welcome_user() {
    return "<p>Welcome to Green Hills Community Center</p>";
}
